# Generated by Django 3.2.9 on 2021-12-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
