# Generated by Django 3.2.9 on 2021-12-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0003_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='poke',
        ),
        migrations.AddField(
            model_name='poke',
            name='destination_user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_pokes', to='poke_app.user'),
        ),
        migrations.AddField(
            model_name='poke',
            name='origin_user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_pokes', to='poke_app.user'),
        ),
    ]
